### ISSUE TITLE
Data lost in browser when CanZone.current finishes

### ISSUE THREAD

**Issue by marshallswain** [canjs/can-zone-storage#2]
It appears that when the current zone is done processing, CanZone.current is disposed of, which removes any data that was written to it.  This causes data written into the CanZone.current.data to be lost.

**Comment by justinbmeyer** [comment]
Shouldn't it be lost?

**Comment by marshallswain** [comment]
The problem happens in the browser.  In between when it gets set and when it gets read it gets erased, so the app never shows logged in.

**Comment by justinbmeyer** [comment]
Are you talking about re-attachment?

**Comment by marshallswain** [comment]
It might be re-attachment related.  All I know is that the following sequence is happening.

1. There is a CanZone.current when the app is initializing.
2. When no auth data is found in zoneStorage, the `Session.get()` runs and populates auth data into `zoneStorage` in `CanZone.current.data`.
3. `CanZone.current` completes and gets erased. (Probably at about the same time that re-attachment is happening.)
4. The app does a `zoneStorage.getItem(‘can-connect-feathers-session')` and since there *is* a `window.CanZone`, but no longer a `CanZone.current`, it’s unable to find the data that was previously stored there.  Auth fails.

We either need a way to detect the zone completing (or the re-attachment if that’s the issue) and moving the data to a place that persists (probably not a good idea for the Done-SSR environment) or we need to give it a method to detect that it’s loaded in a real browser and only use the internal data store.
